platform :ios, '10.0'

target 'Swift Chat iOS13' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swift Chat iOS13
  pod 'CLTypingLabel', '~> 0.4.0'
  # add pods for desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  
end
